name: pin_optimize_app
description: A sample command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.8.1
  quiver: ^3.2.1
  # expandable_quadtree:
  #   path: ../expandable_quadtree

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.8
  freezed: ^2.2.0
  json_serializable: ^6.3.1

assets:
  - assets/beri_zaryad_msk.json
